# Generated by Django 3.1.7 on 2021-03-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('song', 'song'), ('podcast', 'podcast'), ('audiobook', 'audiobook')], default='song', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('participants', models.JSONField(blank=True, max_length=1100, null=True)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audio.audiofile')),
            ],
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_of_title', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='audio.audiofile')),
            ],
        ),
    ]
